version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  myserver:
    build: .
    ports:
      - "8080:8080"
    environment:
      POSTGRES_CONN_STR: "postgres://user:password@postgres:5432/mydb?sslmode=disable"
    depends_on:
      - postgres

volumes:
  postgres_data:
